### ISSUE TITLE
no result with rx_sdr

### ISSUE THREAD

**Issue by guy426** [xaelsouth/rtl-wmbus#32]
I using sdrplay.
Command line is:  rx_sdr  -d "driver=sdrplay" -g IFGR=20,RFGR=0 -f 868.95M -s 1000k - | rtl_wmbus_x86
No output but there are many wmbus equipment in area. rtl_433 decode it well.
Samples attached.

Using rtlsdr all works
[samples.zip](https://github.com/xaelsouth/rtl-wmbus/files/8472979/samples.zip)
.

**Comment by xaelsouth** [comment]
Hi, try to set the sample rate to 1600k, just like that (not checked ):

 rx_sdr -d "driver=sdrplay" -g IFGR=20,RFGR=0 -f 868.95M -s 1600k - | rtl_wmbus_x86
