### ISSUE TITLE
Test with IZAR RC 434 I R4

### ISSUE THREAD

**Issue by almerindo** [xaelsouth/rtl-wmbus#38]
I would like to try with the module [IZAR RC 434 I R4](https://www.diehl.com/metering/en/products-services/system-software/system-software-components/izar-rc-i-r4-at/)  **model - 434MHz.**

The following command didn´t work:
rtl_sdr -f 434M -s 1600000 - 2>/dev/null | build/rtl_wmbus

Can you help me?

**Comment by xaelsouth** [comment]
Hello almerindo,

I'm sorry, but what you want to do - it will not work. According to
https://www.diehl.com/metering/en/products-services/system-software/system-software-components/izar-rc-i-r4-at/ your device is sending in R-mode (R3 or R4?) WmBus mode, which is not implemented now.

FYI: Appendix of https://www.ti.com.cn/cn/lit/an/swra423/swra423.pdf contains a nice summary of  all possible OMS (WmBus) modes.

Xael

**Comment by almerindo** [comment]
Hi!  I tried with the right frequency in 434.47 MHz (R3 mode)  and It is working now!

```
rtl_sdr -f 434.47M -s 1600000 - 2>/dev/null | ./build/rtl_wmbus 
```

The output:
```
T1;1;1;2022-08-23 23:20:57.000;127;162;0106741C;0x1344304c1c7406018800a04114001300aa3afd3c
T1;1;1;2022-08-23 23:20:57.000;144;158;0106741C;0x1344304c1c7406018800a04114001300aa3afd3c
T1;1;1;2022-08-23 23:21:06.000;125;131;0106741C;0x1344304c1c7406018800a05114001300bd15b497
T1;1;1;2022-08-23 23:21:06.000;141;166;0106741C;0x1344304c1c7406018800a05114001300bd15b497
```

I used the  [wmbusmeters](https://github.com/weetmuts/wmbusmeters) and now I'm getting all wattermeter of my neighbors :-D

```
wmbusmeters --debug --t1 rtlwmbus:434.47M
``` 

Output:
```
...
(telegram) TPL CI=a1
Received telegram from: 01067447
          manufacturer: (SAP) Sappel (0x4c30)
                  type: Water meter (0x07)
                   ver: 0x00
                device: rtlwmbus[00000001]
                  rssi: 125 dBm
                driver: izar
(wmbus) 000   : 19 length (25 bytes)
...
``` 

Thanks !

**Comment by xaelsouth** [comment]
Ок, I thought that this water meter would be sending consumption values in R Mode, which is currently not supported by rtl-wmbus. Bit it was a "usual" T1 Mode. Sorry for having put some irritations into it ;)
