### ISSUE TITLE
Wrong behaviour on stadout

### ISSUE THREAD

**Issue by alvaromemo** [xaelsouth/rtl-wmbus#44]
Running this command was working great

`rtl_sdr -f 434.475M -s 800000 - 2>/dev/null | /usr/bin/rtl_wmbus -p s`

But suddenly starts showing this.

![image](https://github.com/xaelsouth/rtl-wmbus/assets/34141161/620d6b96-1d40-4d3e-94b4-387613d9d0dc)

Running this command

`wmbusmeters rtlwmbus:434.475M:t1 Sappel izar ANYID ANYKEY`

Shows this.

![image](https://github.com/xaelsouth/rtl-wmbus/assets/34141161/10bfbece-6fb6-4561-bc1e-00adab6c07be)

Why this happens and how i restart the rtl_wmbus service?

**Comment by alvaromemo** [comment]
I have to reinstall `wmbusmenters` and works again. Any ideas?.

**Comment by xaelsouth** [comment]
Hello alvaromemo.

No ideas, but you are trying to use rtl_sdr and rtl_wmbus in a strange way:
rtl_sdr -f 434.475M -s 800000 - 2>/dev/null | /usr/bin/rtl_wmbus -p s

You have given the sample rate as 800000. In that case you need to pass "-d 1" to rtl-wmbus.
And you have passed a "s" argument, you probably wanted "-s", but do you really want to receive S1, T1 and C1 at 434MHz?..
