### ISSUE TITLE
rtl_wmbus cannot read from rtl_sdr -- how to debug -- or can it use rtl_433 instead ?

### ISSUE THREAD

**Issue by stbuerger** [xaelsouth/rtl-wmbus#45]
Hello - I' m facing a strange problem with rtl_wmbus. The facts are ..
- rtl_433 correctly receives and decodes transmission from my Kamstrup Multical 21 water meter
  `rtl_433 -f 868.625M -s 1600000 -R 104 -R 105 `
- `rtl_sdr -f 868.625M -s 1600000` produces _some_ output 
- `rtl_sdr -f 868.625M -s 1600000 | rtl_wmbus -s` doesn't produce any output
- `cat samples.bin | rtl_wmbus` works fine (samples.bin from repo/source)

The question I now have
1) How can I further debug this ? How can I "validate" output from rtl_sdr ?
2) Could I somehow use "raw" data from rtl_433 to feed to rtl_wmbus ?

I know I can use rtl_433 as device/input for wmbusmeters (and got it working) but would prefer to use rtl_wmbus.
(Can't get correct RSSi from rtl_433)

thx a lot

-sb

**Comment by xaelsouth** [comment]
Hello.

From Multical  21 I know that the meter works in C1/T1 mode only. So try to receive at 868.95MHz and tell rtl-wmbus by omitting the "-s" parameter in _ITS_ command line only to look for T1/C1 datagrams. That will be less CPU exhaustive and probably achieves a slightly better sensitivity:

rtl_sdr -f 868.95M -s 1600000 - 2>/dev/null | build/rtl_wmbus

To "validate output from rtl-sdr". Well, you will _ALWAYS_ get something, even noise. So there is no way to validate whether your meter's signal is in there.

Also, there is no need or way to feed raw data from rtl_433 to rtl-wmbus. rtl_433 seems to control the RTL dongle by itself, whereas rtl_wmbus relies on rtl_sdr and acts like a filter receiving all its data from rtl_sdr.

**Comment by xaelsouth** [comment]
... and make sure you have put '-'  (a minus) in the command line which means that rtl_sdr will redirect its output to stdout!

**Comment by xaelsouth** [comment]
I nothing worked until now, please check out with the new version of rtl_wmbus. I'm gonna close this issue.
