### ISSUE TITLE
wmbus Mode T: some bits look strange

### ISSUE THREAD

**Issue by kralo** [xaelsouth/rtl-wmbus#48]
I have a sample capture, that can be decoded by rtl-wmbus, but some bits look strange and `3of6ok` is not ok.
```
$ cat 48_sample.cu8 |  rtl_wmbus -d 3 -s
T1;0;0;2024-03-26 21:22:31.000;63;69;FFFF8569;0x294468506985ffffffffffffff2f61ffffffffff0080ff000109ffffffffffffffffff009ed400ffffff
```
[48_sample.cu8.zip](https://github.com/xaelsouth/rtl-wmbus/files/14764815/48_sample.cu8.zip)

I then reported to rtl_433, that their decoder could not decode anything, now with improvements from the code from the [merbanan/rtl_433/pull/2883](https://github.com/merbanan/rtl_433/pull/2883) it decodes plausible values,
```
$ rtl_433/build/src/rtl_433 -s 2400k -R 104:vv -r 48_sample.cu8 
rtl_433 version 23.11-99-gf3f2e9f0 branch master at 202403262131 inputs file rtl_tcp RTL-SDR
[Input] Test mode active. Reading samples from file: 48_sample.cu8
[m_bus_mode_c_t_callback] PREAMBLE_T: found at: 75
codes     : {687}800a2aaaaaaaaaaaaaaa87a74ae38d58cacd4b6326b4d2c9b54ad8b94a732cb2d2d2752d1a5acb2c6d8d1a5acb2d62cd1ab2cb1ab4b496b4cb2cd4731ab2c9e919cb2d663a16b2d2e58b8b2cb53932b2d2b51cd00002
[m_bus_mode_c_t_callback] M-Bus: Mode T
[m_bus_mode_c_t_callback] Experimental - Not tested
[m_bus_mode_c_t_callback] MBus telegram length: 49
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
time      : @0.030594s
model     : Wireless-MBus Mode      : T            Manufacturer: TCH         ID        : 60168569
Version   : 118          Device Type: 0xF0         Device Type String:       Control   : 0x44          Data Length: 42
Data      : 274468506985166076f0a0009f2f613000186130008061000109006ba1007cb2008dc3009ed4000fe50096ba   Integrity : CRC

[pulse_slicer_pcm] Wireless M-Bus, Mode C&T, 100kbps (-f 868.95M -s 1200k)
codes     : {687}800a2aaaaaaaaaaaaaaa87a74ae38d58cacd4b6326b4d2c9b54ad8b94a732cb2d2d2752d1a5acb2c6d8d1a5acb2d62cd1ab2cb1ab4b496b4cb2cd4731ab2c9e919cb2d663a16b2d2e58b8b2cb53932b2d2b51cd00002

```

... which looks quite right.

But might the rtl-wmbus deocder also be imroved to decode the same?

**Comment by xaelsouth** [comment]
Hello kralo,

check out the new version of rtl_wmbus. Got this output with  your file attached.

cat 48_sample.cu8  | build/rtl_wmbus -d 3 -s -o
T1;1;1;2024-05-09 15:57:39.000;63;69;60168569;0x294468506985166076f0a0009f2f613000186130008061000109006ba1007cb2008dc3009ed4000fe500
T1;1;1;2024-05-09 15:57:39.000;70;68;60168569;0x294468506985166076f0a0009f2f613000186130008061000109006ba1007cb2008dc3009ed4000fe500
