### ISSUE TITLE
Add support for N1 and N2 169MHz wmbus telegrams. #10

### ISSUE THREAD

**Issue by marcomilazzo** [xaelsouth/rtl-wmbus#5]
do you plan to read the 169MHz narrow-band wm-bus?
marco

**Comment by xaelsouth** [comment]
No such plans, I don't have any meter which would be using N-Mode at 169 MHz.

As I know, N-mode is mostly for current meters, using GFSK modulation with lower baudrate and higher tx power for reaching wider range. It should not be very hard to suport it.

**Comment by optiluca** [comment]
Hi.  I would also be interested in this functionality, I have a RTL-SDR receiver and my gas meter is an AEM G4 EUS which runs in N-Mode @ 169MHz.  I'd be happy to test code, but unfortunately lack the skillset to actually have a go at implementing this myself...
